### ISSUE TITLE
Clarification for comment

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/casper#102]
https://github.com/ethereum/casper/blob/42f32e5bdd6e16f5b13a65363f2523ee22668b49/casper/contracts/simple_casper.v.py#L33

Comment refers to signature/validation address but the assertion on line 299 references the withdrawal address.

My understanding is that `validator_indexes` tracks withdrawal addresses to avoid duplicate validators and the comment should be changed to reflect this.

However it would seem that the `delete_validator` function removes the contract's ability to track this over time; so if someone can confirm the right behavior then I'm happy to make a PR to reflect this comment change.

**Comment by ChihChengLiang** [comment]
your proposed change makes sense to me.

It seems `validator_indexes` was originally designed to [track signature address](https://github.com/ethereum/casper/commit/a37f96ed20c7f0d11df1513379e0dfb5db93d6f7#diff-5907966b02ce3d72c8259ba4206c1338R21), then it was changed to [track withdrawal address](https://github.com/ethereum/casper/commit/175c4d8d53c604369a03843489fdba6e0451835c) next week.

**Comment by darcius** [comment]
This might help shed some light on that change guys https://github.com/ethereum/casper/pull/21
