### ISSUE TITLE
Update pyrlp version

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/casper#111]
## Issue

Recently the pyrlp upgraded to 1.0.0-beta and introduced some breaking changes, such as removing `encode_hex` and `decode_hex` functions https://github.com/ethereum/pyrlp/pull/55 .

## Suggested implementation

- upgrade `rlp >= 1.0.0-beta` in `requirements.txt`
- replace all broken functions in the codebase with functions from https://github.com/ethereum/eth-utils .

**Comment by hrishikeshio** [comment]
There are dependency issues https://github.com/ethereum/pydevp2p/pull/95

casper depends on pydevp2p which requires rlp<1. This is because devp2p is python2 and python3 compatible but rlp>1 and eth_utils are not compatible with python3.

**Comment by djrtwo** [comment]
Thanks for looking into this!

**Comment by djrtwo** [comment]
Any update on this one?

**Comment by hrishikeshio** [comment]
@djrtwo. It's blocked. How do we proceed? We have to make pydevp2p python 3 only... Is that ok?

**Comment by ChihChengLiang** [comment]
ah ... sorry @hrishikeshio , most of the packages in `requirements.txt` are not required now. The pydevp2p was used by a casper daemon that is removed recently. I'll clean up the `requirements.txt` and you should able to work on this soon.

**Comment by hrishikeshio** [comment]
Thanks guys. But now it seems pyethereum upgraded to rlp 1 only in the very recent commit. and the build is failing. https://github.com/ethereum/pyethereum/commit/6c7cf77182c43fe50bf7def773bbf9db8cc6d1f8

Created this issue.
https://github.com/ethereum/pyethereum/issues/876

**Comment by hrishikeshio** [comment]
Now its blocked because of this https://github.com/ethereum/pyethereum/issues/879

**Comment by djrtwo** [comment]
This is going to be fixed in #150 becuase I am getting rid of the pyethereum dependency. I'll take it from here. Thanks for your help digging @hrishikeshio

**Comment by djrtwo** [comment]
addressed in #150
