### ISSUE TITLE
Use keccak256

### ISSUE THREAD

**Issue by ethers** [ethereum/casper#12]
... when Viper implements it https://github.com/ethereum/viper/issues/267

**Comment by ajthenewguy** [comment]
Look at the linked ticket:

> vbuterin commented on Jul 10
> Done.

**Comment by charles-cooper** [comment]
Sorry if this is a very basic question since I'm a newbie - does this mean to use keccak256 instead of delegating hashing to `sighasher` (e.g. https://github.com/ethereum/casper/blob/2901ed1856bc78ce1beff8a04d2d669d4b6d5f98/casper/contracts/simple_casper.v.py#L309)?
