### ISSUE TITLE
"Invalid Type" Error when compiling with Vyper

### ISSUE THREAD

**Issue by KForgette238** [ethereum/casper#126]
Trying to compile the contract with Vyper yields the following error:

vyper.exceptions.InvalidTypeException: line 263: Invalid type: "Compare(left=Name(id='bytes', ctx=Load()), ops=[LtE()], comparators=[Num(n=1024)])"
def validate_signature(sighash: bytes32, sig: bytes <= 1024, validator_index: int128) -> bool:

Has anyone else run into this issue and know how to fix it?

**Comment by djrtwo** [comment]
In the master branch of Vyper, they've updated some of the type declaration syntax. We're currently using vyper version 0.0.4 found here https://github.com/ethereum/vyper/releases/tag/v0.0.4

Make sure you are using the code from that release and try again.

**Comment by djrtwo** [comment]
Closing. Let me know if this did not fix your issue

**Comment by KForgette238** [comment]
Thanks for getting back to me so quickly. I tried using v 0.0.4 of Vyper, but I'm running into additional problems now. I can run "make" successfully, but when I run "make test", I get the following error:

3-py3.6.egg/ethereum/utils.py", line 13, in <module>
    from rlp.utils import decode_hex, encode_hex, ascii_chr, str_to_bytes
ImportError: cannot import name 'decode_hex'

There is an open issue for this exact error under the v 0.0.4 release but no one has responded in a couple of days. The issue also suggested trying to install using the docker file. I'm able to generate the container, but I can't run the make command within in to actually build vyper.

Any suggestions?

I'm trying to build vyper 0.0.4 under the following conditions:
OS: High Sierra 10.13.4
Python 3.6.5
Running a virtual environment of python with virtualenv 15.2.0
Or using Docker version 18.03.1-ce, build 9ee9f40

**Comment by djrtwo** [comment]
Looks like you are using old commands from the setup.py file? We are currently removing that method.

Follow the commands in the README:
`pip3 install -r requirements.txt` to build
and
`pytest tests` to test

**Comment by ascjones** [comment]
@KForgette238 I was also struggling with this but used @djrtwo's instructions above (in the *casper* repo, not vyper) allowed me to the run the 0.0.4 vyper compiler from within the casper virtualenv.
