### ISSUE TITLE
ubuntu install issue

### ISSUE THREAD

**Issue by subhasisbanik** [ethereum/casper#139]
Ran the below command:
pip3 install -r requirements.txt

And got the issue:

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-q7ledi1k/scrypt/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-vp4e__kd-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-q7ledi1k/scrypt/

Please help.

**Comment by subhasisbanik** [comment]
I am running Ubuntu 16.04 and have installed,
sudo apt-get install build-essential libssl-dev python-dev
Now its not throwing error.
"Successfully installed asn1crypto-0.24.0 bumpversion-0.5.3 cffi-1.11.5 coincurve-7.1.0 coverage-4.5.1 ethereum-2.3.0 future-0.16.0 pbkdf2-1.3 py-ecc-1.4.2 pycparser-2.18 pycryptodome-3.6.1 pyethash-0.1.27 pytest-cov-2.5.1 pytest-runner-4.2 scrypt-0.8.6 vyper-0.0.4"

How to run the setup now?

**Comment by djrtwo** [comment]
So you've successfully installed the dependencies? You should try running the test suite with:

```python
pytest tests
```

**Comment by djrtwo** [comment]
Closing. Let me know if this did not fix your issues and I'll reopen.
