### ISSUE TITLE
next_validator_index comment is misleading

### ISSUE THREAD

**Issue by paulhauner** [ethereum/casper#144]
https://github.com/ethereum/casper/blob/100c1b4e1e816b6362c7f2d810d78b2ef21c3031/casper/contracts/simple_casper.v.py#L29

This var does not represent the number of validators as it is set to `1` in the constructor. It technically represents `number of validators + 1`.

I would suggest changing the comment to "Next available validator index.", however I am no authority :smile:

**Comment by ChihChengLiang** [comment]
the comment "Next available validator index." sounds good!

**Comment by djrtwo** [comment]
It doesn't even represent the number of validators + 1! It represents the number of validators there have ever been (+ 1)... 

changing it now
