### ISSUE TITLE
Suggestion: rename the repo to Casper-FFG

### ISSUE THREAD

**Issue by jamesray1** [ethereum/casper#155]
To differentiate it from Casper CBC

**Comment by ChihChengLiang** [comment]
A concern is that this repo has been referenced in many docs. The effect of the rename could be non-trivial. 
Can add more hint in the `README.md` tough.

**Comment by jamesray1** [comment]
Sure, I should've mentioned to see if there was a way to set up a redirect link for https://github.com/ethereum/casper to https://github.com/ethereum/Casper-FFG.

**Comment by jamesray1** [comment]
After renaming this repo to Casper-FFG you could also create a new casper repo, with just a README.md that directs people to https://github.com/ethereum/Casper-FFG.

**Comment by djrtwo** [comment]
I'm inclined to leave this as and only address if/when cbc is in more active development as an actual eth protocol

**Comment by jamesray1** [comment]
Find more devs to work on Casper CBC ;). We'll need it for energy efficiency, security, added scalability, etc. I'd work on it if it wasn't for needing to develop sharding first anyway, since it's probably easier to integrate sharding then Casper CBC rather than vice versa.
