### ISSUE TITLE
Withdraw reward separately

### ISSUE THREAD

**Issue by aykay82** [ethereum/casper#17]
Hi,
I am not sure if it would significantly increase the complexity and the costs of the contract. But if not it would be great if you could withdraw the reward separately. This should be optional. When someone choses this method the reward wouldn't be used for staking and not added to the deposit but to a different variable.
Thanks

**Comment by djrtwo** [comment]
The current economic model and proofs assume that rewards are not withdrawn. Please bring this up in http://ethresear.ch if you want to discuss further.
