### ISSUE TITLE
TODO & questions for `simple_casper.v.py`

### ISSUE THREAD

**Issue by jonchoi** [ethereum/casper#28]
Did a read of the latest code, and here are some questions and suggested next steps. Will be tackling it myself. Thanks to @karlfloersch and @vbuterin for answering tons of questions along the way.

[HackMD Link](https://hackmd.io/IYDgDATALGCcsFpgGMCMATBUrpAgRsgMzIIDsAZmFBRLAKYCs+jZQA==?edit)

#### Economic Variables
[] solve @jonchoi
[Source code](https://github.com/ethereum/casper/blob/34503973abceed0f0267fe35e229a40e7a94270a/casper/contracts/simple_casper.v.py)
```

# Withdrawal delay in blocks
withdrawal_delay: num

# Reward for voting as fraction of deposit size
reward_factor: public(decimal)

# Base interest factor
base_interest_factor: public(decimal)

# Base penalty factor
base_penalty_factor: public(decimal)

# Current penalty factor
current_penalty_factor: public(decimal)
```
...

Line 200
```
# Base interest rate.
base_interest_rate = self.base_interest_factor / sqrt
# Base penalty factor
base_penalty = base_interest_rate + self.base_penalty_factor * log_distance

# where sqrt is sqrt of deposits
# and log_distnace is log of ESF
```

```
if self.main_hash_justified:
            resize_factor = (1 + base_interest_rate) / (1 + base_penalty * (3 + 2*non_vote_frac / (1 - min(non_vote_frac, 0.5))))
        else:
            resize_factor = (1 + base_interest_rate) / (1 + base_penalty * (2 + non_vote_frac / (1 - min(non_vote_frac, 0.5))))
```

```
# Delete the offending validator, and give a 4% "finder's fee"
    validator_deposit = self.get_deposit_size(validator_index_1)
    slashing_bounty = validator_deposit / 25
```

#### TODO
[] Periodic withdrawals
[] Help with test coverage
[] Modular initialization code
[] Abstract out `self.total_curdyn_deposits > 0 and self.total_prevdyn_deposits > 0` 
[] Abstract out dynasty math (`assert self.dynasty >= self.validators[validator_index].end_dynasty + 1
` in line 306)
[] refactor `vote`
[] viper. `var`
[] talked with karl about making dynasties only change with validator set changes.
[] abstract out `2/3` constant throughout the code
[] refactor extracting params from votes etc
[] struct/dict for votes? (helpful for unpacking params from serialized format)
[] move finder's fee to constants
[] `addr` to `valcode_addr`

#### Questions
* Revenue / Expense model vs Yield model?
* Recommnedation helpers: Expected hash? `self.expected_source_epoch`
* Why? "If either current or prev dynasty is empty, then pay no interest, and all hashes justify and finalize"
* "Increment the dynasty if finalized" dynasty is every finalized epoch? not change in validator set?
* why does deposit_scale_factor depend on end_epoch?
* naming: `proc_reward`? process reward?
    * we should name `vote` `proc_vote` then? 

#### Comments on code
* ln 148 – outdated comment
* ln 188 – why max of prev and cur?
* why sqrt factor? add comment that we're approximating
* ln 193 – why log of epochs? please explain
* ln 204 – rate + factor? seems like units are off?
* ln 57 - "current expected hash"? (`main_hash_justified`)
* ln 255 – dynasty + 2? 
* ln 251 – extract32? purity checker?
* ln 178 – recommened target hash / where is `blockhash`?
* ln 350 – `assert target_hash == self.get_recommended_target_hash()` why does that feel like a "circular" check?
* ln 365 – "# Record that the validator voted for this target epoch so they can't again" why not allow and slash?
* ln 44 – `votes` isn't clearly an index of votes for each epoch. hmm maybe update comment

**Comment by maxzzze** [comment]
Hey Jon,

Would be happy to help with some of these TODOs. Want to make a branch to work off of that we can all contribute to?

**Comment by maxzzze** [comment]
Also, this repo doesn't have much of an open source policy - if you hadn't noticed. I have a MR from August.

**Comment by hukkinj1** [comment]
Hi everybody,
read the contract just for fun and games. A few questions raised:

Line 257:
```
end_dynasty: 1000000000000000000000000000000,
```
Is this just an arbitrary "large enough to equivalent infinity" number, or is there some other reasoning for it? 

Line 265:
```
# Log in or log out from the validator set. A logged out validator can log
# back in later, if they do not log in for an entire withdrawal period,
# they can get their money out
```
This comment seems outdated to me. Seems like the method no longer does logging in.
