### ISSUE TITLE
validator_service.py should live in this repo

### ISSUE THREAD

**Issue by djrtwo** [ethereum/casper#47]
`validator_service.py` is currently in a fork of the pyethapp repo [here](https://github.com/karlfloersch/pyethapp/blob/dev_env/pyethapp/validator_service.py), but I propose it should be ported to this repo.

`validator_service.py`:
- directly depends on the implementation of the casper contract
- shares dependencies with the casper contract
- is automatically tested in this repo's build

Currently whenever we bump the version of vyper or pyethereum, change a public function name, or most other refactors, we have to update implementation and dependencies simultaneously in the other repo. 

# Proposed implementation
- port `validator_service.py` to either `/daemon` or a new directory `/service`
- update validator_service tests to run locally rather than across repos.
- remove `validator_service.py` from the pyethapp fork

**Comment by djrtwo** [comment]
@karlfloersch thoughts?

**Comment by karlfloersch** [comment]
@djrtwo I agree that if we reimplement `validator_service.py` using web3, it would totally make sense to move it here. Not sure exactly how to handle the old validator service though. Maybe we just build out the new web3 `validator_service.py` and then once that's done look into replacing the old one?

**Comment by djrtwo** [comment]
Works for me. I'll open a new issue around that.

**Comment by djrtwo** [comment]
Closing in favor of #48
