### ISSUE TITLE
delete_validator in simple_casper has no authentication

### ISSUE THREAD

**Issue by pirapira** [ethereum/casper#5]
It seems like `delete_validator` function in `simple_casper.v.py` has no authentication:
https://github.com/ethereum/casper/blob/master/casper/contracts/simple_casper.v.py#L263

Is this a problem?

**Comment by pirapira** [comment]
#3 seems to solve it.

**Comment by djrtwo** [comment]
@pirapira `delete_validator` is currently used by `slash` which would be called by a user other than the validator being deleted. The method has been marked `private` since this issue was created. 

I think we can now close this.

**Comment by pirapira** [comment]
OK.
