### ISSUE TITLE
Delayed Logoff

### ISSUE THREAD

**Issue by djrtwo** [ethereum/casper#51]
# Issue
Changing contract such that logging out kicks a validator out of the validator set 700 dynasties from  call to `logout` rather 2 dynasties. Increases the stitching of current dynasty and previous dynasty.

# Proposed implementation
- Add `dynasty_logout_delay` to casper contract initialization params
- Add `dynasty_wei_delta`: map from dynasty -> (wei / m). This will replace `next_dynasty_wei_delta` and `second_next_dynasty_wei_delta`
- replace references to 2 dynasties in contract with the new `dynasty_logout_delay` param
- Add `logout` and `withdraw` tests that test against different `dynasty_logout_delay` values
- Update casper config in karl's deploy scripts to include the 700 for dynasty logout (not exactly sure where to do this. will add when I find it.)

# Questions
- re-read the paper on "forward" and "rear" validator sets. cur and prev dynasty should operate as is. This just pushes the `end_dynasty` back

**Comment by ChihChengLiang** [comment]
is this the deploy scripts of casper config you looking for? https://github.com/karlfloersch/pyethapp/blob/dev_env/pyethapp/eth_service.py#L171

**Comment by djrtwo** [comment]
Yes! Thanks :)

**Comment by djrtwo** [comment]
Added question about how this affects the "prev dynasty"
cc: @vbuterin @karlfloersch @ChihChengLiang

**Comment by djrtwo** [comment]
addressed in #56
