### ISSUE TITLE
Add logging for asserts in contract

### ISSUE THREAD

**Issue by djrtwo** [ethereum/casper#52]
# Issue
Although they plan on adding support (https://github.com/ethereum/vyper/issues/523), Vyper currently does not support logging when asserts fail.

# Proposed implementation
- create a method `assert_and_log(conditon, message)`
- Migrate all calls from `assert` to `assert_and_log` to aid in debugging the test net

NOTE: This code has not been tested.

```python
Error: __log__({message: bytes <= N})

@private
def assert_and_log(condition: bool, message: bytes <= N):
    if condition:
        log.Error(message)
        assert(False)

def some_method(val: num):
    assert_and_log(num < 5, b'The number passed into `some_method` is not less than 5')
```

We need to decide on a value for the max bytes length of error strings.

**Comment by djrtwo** [comment]
I haven't worked with strings in vyper before. I think something like the above works for the error message.

Also looks like theres a `concat` method that will be useful in constructing error messages.

**Comment by zilm13** [comment]
@djrtwo it will not work, logs are cleared if tx is failed. Stuck with that yesterday, where are damn logs in receipt??? They are cleared if tx is failed. You couldn't have error log.

**Comment by djrtwo** [comment]
A very ugly way to log specific failed conditions would be:

```python
@public
def some_method():
    if not condition:
        log.Error(message)
        return
```

This would only be even close to reasonable at the beginning of a call to a public method before anything else has occurred because it wouldn't revert state. Seems too dangerous to start meddling with the contract like that.

**Comment by djrtwo** [comment]
Closing this tomorrow unless anyone else has a reasonable idea.

**Comment by zilm13** [comment]
@djrtwo yeah you could make it success just for logs but it's an easy way to make mistakes. You need to reset everything done before by hands etc. Doesn't worth it.
