### ISSUE TITLE
Migrate types from `num` to `int`

### ISSUE THREAD

**Issue by djrtwo** [ethereum/casper#53]
# Issue
`num` and `num256` type in vyper are being deprecated in favor of `int128` and `uint256`, respectively. 

# Proposed implementation
- convert references of `num` to `int256`
- convert references of `num256` to `uint256`
- convert type casting from `as_TYPE` usage to newer `convert(var, `type`)` format. (all type castings not just `int`/`uint`)
- migrate validator_service.py and update testing accordingly
- ensure vyper up to date such that it can handle these types

**Comment by BenKaufman10** [comment]
Regarding the 3rd point, not sure I understood what you mean correctly but anyway just as a small fix/ reminder, I'm pretty sure `as_uint256` doesn't exist anymore.
Currently you should use `convert(your_var, 'uint256')` instead.

**Comment by djrtwo** [comment]
Was referencing the note about "integer literals" in the vyper types documentation here https://github.com/ethereum/vyper/blob/master/docs/types.rst#unsigned-integer-256-bit

**Comment by djrtwo** [comment]
We use that a few times in the casper contract like

```python
assert not bitwise_and(self.votes[target_epoch].vote_bitmap[target_hash][validator_index / 256],
                           shift(as_num256(1), validator_index % 256))
```

on [line 388](https://github.com/ethereum/casper/blob/master/casper/contracts/simple_casper.v.py#L387)

**Comment by BenKaufman10** [comment]
The problem is the docs are not up to date, I am currently working on updating and improving them.
So this `as_num256(1)` should be changed to this: `convert(1, 'uint256')`.
(You can see if you try to compile with `as_uint256()` it will give an error)

**Comment by djrtwo** [comment]
Thanks! I was just about to add a comment that although I think this is
correct, sometimes I have to dig into the code to see what's actually up to
date.

Updating the issue now

**Comment by djrtwo** [comment]
Closing in favor of #63
