### ISSUE TITLE
Decouple testing between /casper and /pyethereum

### ISSUE THREAD

**Issue by djrtwo** [ethereum/casper#59]
# Issue
I think we should decouple testing between the casper repo and the pyethereum/pyethapp repo. It makes getting certain builds to pass before merging impossible. For example because the constructor signature changes in #56, I have to modify pyethereum before the build passes, but to modify pyethereum, I need to updated code!

A better workflow would be:
- update casper contract, tests pass, merge
- update pyethereum to point to updated casper contract
- fix/modify repo as necessary such that tests in pyethereum pass

# Proposed implementation
- Remove reference to docker and pyethereum tests from .travis.yml
- Add an auto-travis build to /pyethereum
- (consider moving dev on /pyethereum back to ethereum/pyethereum)

**Comment by djrtwo** [comment]
@ChihChengLiang This is a blocker on merging updates/fixes. Let me know what you think

**Comment by ChihChengLiang** [comment]
These two sounds great
```
Remove reference to docker and pyethereum tests from .travis.yml
Add an auto-travis build to /pyethereum
```

pyethereum is soon to be deprecated, not sure if this worth it.
```
(consider moving dev on /pyethereum back to ethereum/pyethereum)
```
