### ISSUE TITLE
`vote_bitmap` does not need to map from `target_hash`

### ISSUE THREAD

**Issue by djrtwo** [ethereum/casper#62]
# Issue
`vote_bitmap` contained within the `votes` struct current has the following type. We use the `target_epoch` to select the `votes` struct and then `vote_bitmap` is a mapping from a `target_hash` to a vote bitmap:

```python
vote_bitmap: num256[num][bytes32]
```

The `target_hash` (`bytes32`) component of the mapping is no longer necessary. When a vote is cast, we assert that the `target_hash` and `target_epoch` must be that of the `current_epoch`, locking these two fields together. We can and should remove the `bytes32` component of the `vote_bitmap` type def because the only entry into a `target_epoch`s `vote_bitmap` will be for the single corresponding `target_hash`.

# Proposed Implementation
- Remove `[bytes32]` from the `vote_bitmap` typedef
- Fix calls to the `vote_bitmap` throughout the contract accordingly.

**Comment by vbuterin** [comment]
Agree!

**Comment by djrtwo** [comment]
addressed in #82
