### ISSUE TITLE
When total deposit falls to zero, divide-by-zero happens

### ISSUE THREAD

**Issue by pirapira** [ethereum/casper#7]
In `simple_casper.v.py`, in `initialize_epoch`, when `self.total_deposits[self.dynasty]` is zero, `sqrt` becomes zero, and
```
        sqrt = (sqrt + (ether_deposited_as_number / sqrt)) / 2
```
will cause divide-by-zero.

**Comment by djrtwo** [comment]
This is handled [here](https://github.com/ethereum/casper/blob/dcf4caf35937800b04c6bac4a2ab13c1513b6147/casper/contracts/simple_casper.v.py#L383) by ensuring that `deposit_exists()` before doing the calculation that could create the divide by zero.

Closing!
