### ISSUE TITLE
Question/ Possible bug in voting 

### ISSUE THREAD

**Issue by alex687** [ethereum/casper#78]
Hello, 
  `  if (current_dynasty_votes >= self.total_curdyn_deposits * 2 / 3 and
            previous_dynasty_votes >= self.total_prevdyn_deposits * 2 / 3) and \
            not self.votes[target_epoch].is_justified:
`
My question is shouldn't  **total_curdyn_deposits_scaled** be used instead of **total_curdyn_deposits** ?
 I think that with this code if validator goes offline there will be no finalization.

**Comment by vbuterin** [comment]
No, because all balances are stored in `wei / m` units. The unit checker in Vyper enforces this and prevents accidentally comparing one with the other.

**Comment by alex687** [comment]
Yes, I didn't saw that `total_curdyn_deposits_scaled  ` was returning different unit. Correct me if I'm wrong but still I don't see any **"inactivity leak of the deposits"** in the code if validators go offline.

**Comment by djrtwo** [comment]
There is an inactivity leak:

The rewards and penalties are applied individually and collectively:

Individually, when a voter votes, their unscaled deposit instantly increase `validator.deposit *= 1 + reward_factor`

Collectively, every validators' deposits get rescaled

`deposit_scale_factor[epoch] = deposit_scale_factor[epoch - 1] * (1 + vote_fraction * reward_factor / 2) / (1 + reward_factor)`

As a result, validators who have voted, their rescaled deposit are multiplied by `1 + vote_fraction * reward_factor / 2`, while those who haven't are by `(1 + vote_fraction * reward_factor / 2) / (1 + reward_factor)`.

The extra factor in the denominator handles the leak. I agree it is a bit opaque when just reviewing the code.

**Comment by djrtwo** [comment]
Closing. Let us know if you find anything/have any more questions.
