### ISSUE TITLE
Safety of insta_finalization when deposit doesn't exist

### ISSUE THREAD

**Issue by beneficial02** [ethereum/casper#84]
Though this might be 'too much worrying', I'm wondering about safety before deposit is deposited.

According to simple_casper code, it seems `deposit_exists()` is False at least 3 epochs from the initialization(2 epochs for `start_dynasty` in `deposit`, 1 epoch for the change in `total_prevdyn_deposit`), and the epochs are` insta_finalize()`d.

I understood this as it would be finalized even if some attack happens to PoW chain within the epochs without any verification by validators.

I think this risk could be solved in some way, like initializing casper contract with initial validator node run by core team, which works only for a while(until it has enough number of validators). Or we could postpone the finalization until we have enough validators.

**Comment by beneficial02** [comment]
Oh, I see. I missed that point. Thanks for the clarification and sorry for bothering.

**Comment by djrtwo** [comment]
It is discussed in the [Implementation Guide](https://github.com/ethereum/casper/blob/master/IMPLEMENTATION.md) and will be in the upcoming EIP.

Thanks for the code review! We appreciate any review/questions :)
