### ISSUE TITLE
Use capital letters for constants

### ISSUE THREAD

**Issue by djrtwo** [ethereum/casper#88]
# Issue
## Constant var names
There is no distinction from a style perspective in the difference between variables that change and those that should remain constant. Python coding style usually dictates that constants be defined with uppercase like `CONSTANT_VAR_NAME`. The sharding team has begun to define constants in the SMC this way. See [here](https://github.com/ethereum/sharding/blob/develop/contracts/validator_manager.v.py#L85) for an example.

For the sake of clarity in reading the contract and to keep eth core contracts more uniform, we should move to this style

## spaces between functions
Python style dictates two new lines between functions (unless included within a class). Looks like SMC is using this style convention.

# Proposed Implementation
- Rename all constant vars with uppercase names
- Ensure two new lines between each function declaration.

**Comment by garroadran** [comment]
I can help out with this if you'd like. Shall I just send in some PRs or would you like to assign me a specific directory to work on, or something like that?

**Comment by djrtwo** [comment]
Hi @garroadran! looks like there are a couple of PRs already queued up for this. Low hanging fruit with "good first issue" motivated a bunch of people :)

Let me know if you want to pick up any of the other issues in the repo

**Comment by djrtwo** [comment]
addressed in #89

**Comment by garroadran** [comment]
Ah, thanks for that. Sorry I couldn't be of help this time. I will have a look around to see if there's anything else I might be able to lend a hand with.
