### ISSUE TITLE
Variable min deposit size to promote consistent # of vals

### ISSUE THREAD

**Issue by djrtwo** [ethereum/casper#95]
# Issue
Defining an explicit, unchanging value for the minimum size of deposits is risky because we do not have a clear idea as to how many validators will show up. Instead, we want to define a base deposit value and have the minimum a validator needs to deposit scale as the number of validators scales.

# Proposed Implementation
- Track number of active validators with a new contract variable `num_validators` set to 0 at contract creation
- When validator sends deposit `assert msg.value >= max(self.min_deposit_size, num_validators)`
- Increment `num_validators` when a new validator sends a `deposit`
- Decrement `num_validators` when a validator submits a `logout` or is slashed (if they haven't logged out already)

**Comment by darcius** [comment]
Just to add a little bit onto this, can the MIN_DEPOSIT_SIZE be a public variable so it can be accessed externally? Currently it's not (would be nice to have it now too :) and if it could potentially change depending on the number of validators logged in, this would def be needed.

**Comment by djrtwo** [comment]
I exposed the method `current_min_deposit_size` as a public method in the PR. This should probably suffice, right?

 https://github.com/ethereum/casper/pull/98/files#diff-5907966b02ce3d72c8259ba4206c1338R302

**Comment by darcius** [comment]
Ah didn't spot that in the PR @djrtwo, that's perfect. Thanks!

**Comment by darcius** [comment]
Since this PR is closed now due to complexities with it, any chance `min_deposit_size` can be exposed in the current Casper? Happy to submit a PR if that's not an issue :)

**Comment by ChihChengLiang** [comment]
PR is welcome, remember to fix [this comment](https://github.com/ethereum/casper/blob/master/casper/contracts/simple_casper.v.py#L114) in the PR too. That comment only makes sense in the dynamic min deposit size context.

**Comment by djrtwo** [comment]
Closing due to complexities that arise in handling val_count if a validator just goes offline forever.

Proposed solutions to this problem include:
* forced validator rotation on some timescale
* incentivized external actors to logout inactive validators after some time of inactivity

These solutions require more research and development and are being tabled for hybrid casper FFG. Without observing validators in a live network, digging into a solution to this "problem" seems like a premature optimization.
